### ISSUE TITLE
Promise not defined

### ISSUE THREAD

**Issue by kumarnmanoj** [axemclion/IndexedDB#1]
Cannot call method 'promise' of undefined

While executing the create object store in "http://nparashuram.com/IndexedDB/jquery/index.html"

Browser - chrome -> "5.0 (X11; Linux i686) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.57 Safari/534.24"

**Comment by axemclion** [comment]
This page is a little out of date. You should take a look at http://nparashuram.com/trialtool/index.html#example=/IndexedDB/jquery/trialtool.html

**Comment by axemclion** [comment]
Fixed this issue now in commint # afe6a2393d7013884981

**Comment by bdkzero** [comment]
I got the same error also using trialtool or jquery/index.html test page.
[16:55:59] TypeError: Property 'promise' of object #<Object> is not a function 
This error appears opening database, creating transaction, ...

**Comment by axemclion** [comment]
Is the error now fixed ?

**Comment by bdkzero** [comment]
Ok this error now has gone, but running two examples (in both trialTool and index.html) "Open Index and Iterate" and "Key cursor on Index" throws this error:
Uncaught TypeError: Cannot read property 'db' of undefined

Thank you.

**Comment by axemclion** [comment]
Figured out what the error is - Chrome does not support backword linking like objectStore.transaction while firefox does. That is the reason for this error.

**Comment by axemclion** [comment]
Just fixed this in commit  ef33efb6d4684f286794. This was a chrome specific issue.
